#!/bin/bash
#SBATCH -J j6Au_32Co_npo 
#SBATCH -o ll_out          # output file name
#SBATCH -e ll_err	   # output error file 
#SBATCH -n 32              # total number of mpi tasks requested
#SBATCH -p normal
#SBATCH -t 03:00:00        # run time (hh:mm:ss) - 1.5 hours
#SBATCH --mail-user=marcodavidhoward@gmail.com
#SBATCH --mail-type=end    # email me when the job finishes
#SBATCH -A A-chgh

set -x
ibrun ~graeme/bin/vasp_gamma





